#!/usr/bin/python

import sys

import numpy as np
from gnuradio import gr, blocks, zeromq
import fx2adc_swig as fx2adc

def main():
	tb = gr.top_block()

	adc = fx2adc.fx2adc(4, "fx2adc-fw/fx2adc.ihx")

	tb.connect(adc, blocks.tag_debug(32, "fx2pipe", ""))
	tb.connect(adc, zeromq.pub_sink(32, 1, "tcp://127.0.0.1:6000", pass_tags=True))

	tb.run()

if __name__ == "__main__":
	main()
